# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(509, 364)
        Form.setStyleSheet("background-color: rgb(149, 154, 170);")
        self.bt_salir = QtWidgets.QPushButton(Form)
        self.bt_salir.setGeometry(QtCore.QRect(320, 290, 81, 31))
        self.bt_salir.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"selection-background-color: rgb(85, 0, 127);")
        self.bt_salir.setObjectName("bt_salir")
        self.selec1 = QtWidgets.QComboBox(Form)
        self.selec1.setGeometry(QtCore.QRect(30, 150, 91, 22))
        self.selec1.setObjectName("selec1")
        self.selec2 = QtWidgets.QComboBox(Form)
        self.selec2.setGeometry(QtCore.QRect(118, 150, 111, 22))
        self.selec2.setObjectName("selec2")
        self.selec3 = QtWidgets.QComboBox(Form)
        self.selec3.setGeometry(QtCore.QRect(230, 150, 91, 22))
        self.selec3.setObjectName("selec3")
        self.selec4 = QtWidgets.QComboBox(Form)
        self.selec4.setGeometry(QtCore.QRect(320, 150, 91, 22))
        self.selec4.setObjectName("selec4")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(80, 30, 61, 91))
        self.label.setStyleSheet("background-color: rgb(170, 157, 116);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(140, 40, 191, 71))
        self.label_2.setStyleSheet("background-color: rgb(170, 157, 116);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(330, 30, 61, 91))
        self.label_3.setStyleSheet("background-color: rgb(170, 157, 116);\n"
"border-color: rgb(0, 0, 0);\n"
"gridline-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.resultado = QtWidgets.QLabel(Form)
        self.resultado.setGeometry(QtCore.QRect(157, 290, 121, 31))
        self.resultado.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.resultado.setText("")
        self.resultado.setObjectName("resultado")
        self.bt_resultado = QtWidgets.QPushButton(Form)
        self.bt_resultado.setGeometry(QtCore.QRect(40, 290, 111, 31))
        self.bt_resultado.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.bt_resultado.setObjectName("bt_resultado")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 70, 51, 16))
        self.label_4.setStyleSheet("background-color: rgb(85, 0, 0);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(390, 70, 47, 16))
        self.label_5.setStyleSheet("background-color: rgb(85, 0, 0);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label1 = QtWidgets.QLabel(Form)
        self.label1.setGeometry(QtCore.QRect(100, 30, 16, 91))
        self.label1.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label1.setText("")
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(Form)
        self.label2.setGeometry(QtCore.QRect(150, 40, 16, 71))
        self.label2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label2.setText("")
        self.label2.setObjectName("label2")
        self.label3 = QtWidgets.QLabel(Form)
        self.label3.setGeometry(QtCore.QRect(190, 40, 16, 71))
        self.label3.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label3.setText("")
        self.label3.setObjectName("label3")
        self.label4 = QtWidgets.QLabel(Form)
        self.label4.setGeometry(QtCore.QRect(310, 40, 16, 71))
        self.label4.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label4.setText("")
        self.label4.setObjectName("label4")
        self.tolerancia1 = QtWidgets.QLabel(Form)
        self.tolerancia1.setGeometry(QtCore.QRect(80, 230, 61, 31))
        self.tolerancia1.setObjectName("tolerancia1")
        self.resultado_2 = QtWidgets.QLabel(Form)
        self.resultado_2.setGeometry(QtCore.QRect(270, 290, 41, 31))
        self.resultado_2.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.resultado_2.setAlignment(QtCore.Qt.AlignCenter)
        self.resultado_2.setObjectName("resultado_2")
        self.minimo = QtWidgets.QLabel(Form)
        self.minimo.setGeometry(QtCore.QRect(240, 250, 101, 21))
        self.minimo.setStyleSheet("background-color: rgb(205, 244, 255);")
        self.minimo.setText("")
        self.minimo.setIndent(0)
        self.minimo.setObjectName("minimo")
        self.tolerancia = QtWidgets.QLabel(Form)
        self.tolerancia.setGeometry(QtCore.QRect(150, 230, 41, 31))
        self.tolerancia.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.tolerancia.setText("")
        self.tolerancia.setObjectName("tolerancia")
        self.resultado_3 = QtWidgets.QLabel(Form)
        self.resultado_3.setGeometry(QtCore.QRect(320, 250, 31, 21))
        self.resultado_3.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(205, 244, 255);")
        self.resultado_3.setAlignment(QtCore.Qt.AlignCenter)
        self.resultado_3.setObjectName("resultado_3")
        self.resultado_4 = QtWidgets.QLabel(Form)
        self.resultado_4.setGeometry(QtCore.QRect(320, 220, 31, 21))
        self.resultado_4.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(205, 244, 255);")
        self.resultado_4.setAlignment(QtCore.Qt.AlignCenter)
        self.resultado_4.setObjectName("resultado_4")
        self.maximo = QtWidgets.QLabel(Form)
        self.maximo.setGeometry(QtCore.QRect(240, 220, 101, 21))
        self.maximo.setStyleSheet("background-color: rgb(205, 244, 255);")
        self.maximo.setText("")
        self.maximo.setIndent(0)
        self.maximo.setObjectName("maximo")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(360, 222, 47, 13))
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(360, 255, 47, 13))
        self.label_9.setObjectName("label_9")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(90, 380, 161, 111))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.resultado_2.raise_()
        self.bt_salir.raise_()
        self.selec1.raise_()
        self.selec2.raise_()
        self.selec3.raise_()
        self.selec4.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.resultado.raise_()
        self.bt_resultado.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label1.raise_()
        self.label2.raise_()
        self.label3.raise_()
        self.label4.raise_()
        self.tolerancia1.raise_()
        self.minimo.raise_()
        self.tolerancia.raise_()
        self.resultado_3.raise_()
        self.maximo.raise_()
        self.resultado_4.raise_()
        self.label_6.raise_()
        self.label_9.raise_()
        self.label_7.raise_()

        self.retranslateUi(Form)
        self.bt_salir.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Calculo de Resistencia"))
        self.bt_salir.setText(_translate("Form", "Salir"))
        self.bt_resultado.setText(_translate("Form", "RESULTADO"))
        self.tolerancia1.setText(_translate("Form", "Tolerancia: "))
        self.resultado_2.setText(_translate("Form", "Ω"))
        self.resultado_3.setText(_translate("Form", "Ω"))
        self.resultado_4.setText(_translate("Form", "Ω"))
        self.label_6.setText(_translate("Form", "MAXIMO"))
        self.label_9.setText(_translate("Form", "MINIMO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

